version: '3.8'
services:
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
  bot:
    hostname: bot
    image: flea
    env_file:
      - .env
    environment:
      - REDIS_URL=redis
      - POSTGRES_HOST=db
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python -u main.py
    volumes:
      - .:/code
    depends_on:
      - redis
      - db