version: '3.8'
services:
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  bot:
    hostname: bot
    image: flea
    environment:
      - REDIS_URL=redis
      - DATABASE_URL=postgres://postgres:123456@db:5432/postgres
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python -u main.py
    volumes:
      - .:/code
    depends_on:
      - redis
      - db